PORT: 3000
DEFAULT_LOCALE: 'en'
CLEAN_TEMP_FOLDER: true
LOG_TO_FILE: false

MONGO_USERNAME: ''
MONGO_PASSWORD: ''
MONGO_DB_NAME: ''
MONGO_URI: ''

AUTH_SECRET: 'defaultSecret1234'
AUTH_SALT_ROUNDS: 10
AUTH_ACCESS_TOKEN_EXPIRATION: '5m'
AUTH_REFRESH_TOKEN_EXPIRATION: '7d'
AUTH_EMAIL_TOKEN_EXPIRATION: '2h'
AUTH_REGISTRATION_DISABLED: false

EMAIL_MAILGUN_API_KEY: ''
EMAIL_MAILGUN_DOMAIN: ''
EMAIL_FROM_ADDRESS: ''
