PORT: 3000

MONGO_USERNAME: 'daisyDevAdmin'
MONGO_PASSWORD: 'd41syDr0e4dk1n'
MONGO_DB_NAME: 'dev'
MONGO_URI: 'mongodb+srv://<MONGO_USERNAME>:<MONGO_PASSWORD>@daisy-dev-eu-west-1-3ur5u.mongodb.net/<MONGO_DB_NAME>'

AUTH_SECRET: 'defaultSecret1234'
AUTH_SALT_ROUNDS: 10
AUTH_ACCESS_TOKEN_EXPIRATION: '5m'
AUTH_REFRESH_TOKEN_EXPIRATION: '7d'
AUTH_EMAIL_TOKEN_EXPIRATION: '2h'
AUTH_REGISTRATION_DISABLED: false
