PORT: 3000
DEFAULT_LOCALE: 'en'
LOG_TO_FILE: false
CLEAN_LOGS_FOLDER: true
CLEAN_TEMP_FOLDER: true

MONGO_URI: ''

AUTH_SECRET: 'a1'
AUTH_SALT_ROUNDS: 1
AUTH_ACCESS_TOKEN_EXPIRATION: '5m'
AUTH_REFRESH_TOKEN_EXPIRATION: '1d'
AUTH_EMAIL_TOKEN_EXPIRATION: '1h'
AUTH_REGISTRATION_DISABLED: false

EMAIL_MAILGUN_API_KEY: ''
EMAIL_MAILGUN_DOMAIN: ''
EMAIL_FROM_ADDRESS: ''
