
PORT: 3000
BASE_URL: 'http://localhost:3000'
MONGO_URI: 'mongodb://localhost/daisy'
SENTRY_DSN: ''

AUTH_HTTP_ACCESS_USERNAME: ''
AUTH_HTTP_ACCESS_PASSWORD: ''
AUTH_SECRET: 'someRandomThingsHere1234'
AUTH_SALT_ROUNDS: 10
AUTH_ACCESS_TOKEN_EXPIRATION: '7d'
AUTH_EMAIL_TOKEN_EXPIRATION_IN_MINUTES: 120
AUTH_REGISTRATION_DISABLED: false

EMAIL_FROM_ADDRESS: 'no-reply@dev.daisy.com'
EMAIL_MAILGUN_API_KEY: ''
EMAIL_MAILGUN_DOMAIN: ''

DEBUG_RESPONSE_DELAY: 0
DEBUG_NO_CLIENT: false
