PORT: 3000

MONGO_USERNAME: ''
MONGO_PASSWORD: ''
MONGO_DB_NAME: 'daisy'
MONGO_URI: 'http://localhost/<MONGO_DB_NAME>'

AUTH_SECRET: 'defaultSecret1234'
AUTH_SALT_ROUNDS: 10
AUTH_ACCESS_TOKEN_EXPIRATION: '5m'
AUTH_REFRESH_TOKEN_EXPIRATION: '7d'
AUTH_EMAIL_TOKEN_EXPIRATION: '2h'
AUTH_REGISTRATION_DISABLED: false
